import type {Env} from "./vite-env";

export const env: Env = {
    REACT_APP_SERVICE_SERVICE_HOST: import.meta.env.VITE_SERVICE_HOST ?? 'http://localhost:5274',
    REACT_APP_SERVICE_SERVICE_SIGNALR_HUB: '/hubs/notifications',

    REACT_APP_SERVICE_SERVICE_ENDPOINT_LOGIN: '/login',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_REGISTER: '/register',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_REFRESH_TOKEN: '/refresh',

    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS: '/api/projects',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS_ALL: '/all',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS_DETAIL: '/detail',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS_UPDATE: '/update',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS_CREATE: '/create',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS_DELETE: '/delete',

    REACT_APP_SERVICE_SERVICE_ENDPOINT_REPORTS: '/api/reports',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_REPORTS_GENERATE: '/generate',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_REPORTS_DOWNLOAD: '/download',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_REPORTS_PROJECTS: '/projects',

    REACT_APP_SERVICE_SERVICE_ENDPOINT_NOTIFICATION: '/api/notifications',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_NOTIFICATION_READ: '/read',

    REACT_APP_SERVICE_SERVICE_ENDPOINT_STAGES: '/api/stages',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_STAGES_GET_ALL: '/get-all',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_STAGES_DETAIL: '/detail',


    REACT_APP_SERVICE_SERVICE_ENDPOINT_USERS: '/api/users',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_USERS_ALL: '/all',
};

