import type {Env} from "./vite-env";

export const env: Env = {
    REACT_APP_SERVICE_SERVICE_HOST: 'http://localhost:5274',
    REACT_APP_SERVICE_SERVICE_SIGNALR_HUB: '/hubs/notifications',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_LOGIN: '/login',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_REGISTER: '/register',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_REFRESH_TOKEN: '/refresh',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS: '/api/Projects',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS_ALL: '/all',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS_UPDATE: '/update',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS_CREATE: '/create',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS_DELETE: '/delete',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_NOTIFICATION: '/api/notifications',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_NOTIFICATION_READ: '/read',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS_STAGES: '/api/projects',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_STAGES: '/stages',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_REPORTS: 'api/reports',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_REPORTS_GENERATE: '/generate',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_REPORTS_DOWNLOAD: '/download',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_PROJECTS_REPORTS: 'api/projects',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_USERS: 'api/users',
    REACT_APP_SERVICE_SERVICE_ENDPOINT_USERS_ALL: '/all',
};

// (function () {
//     const ev1 = import.meta.env.MODE === 'development' ? env.REACT_APP_SERVICE_SERVICE_HOST : eval('"PROD_ENV_VITE_SERVICES_HOST"');
//
//     env.REACT_APP_SERVICE_SERVICE_HOST = ev1 === '' ? `${window.location.protocol}//${window.location.hostname}:8031` : ev1;
// })();
